minio:
  endpoint: http://10.1.39.95:9000
  accessKey: hL2pqJum98hjDOSu
  secretkey: 2QVNvNuRi0ysJJ3n8Xtj6zBYIQKHJXC9
  bucketName: atom-test


clamav:
  host: 192.168.88.202
  port: 3310
  readTimeout: 20000
  connectionTimeout: 2000

#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
